# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27aa0a9122d686471a43279a10755193894803926009061a704879a47b533d5a51822d37083e839d8e5cd677eb0b62615605337bd8e5a9a6517f30e4ceba7716

test:
  secret_key_base: 22af46a1dbc6e89c4254a4e3437c3011e9e4660d0af7efe8b62a422ff01b91db234f3e190e3059ac84e85ac43eadaa610ef6383a51442f77adfd8a159888d67b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
